name: kitti
disp_name: kitti_eigen_test_full
dir: kitti/kitti_eigen_split_test.tar
filenames: datasets/eval/depth/data_split/kitti/eigen_test_files_with_gt.txt
kitti_bm_crop: true
valid_mask_crop: eigen